config/routes.rb
SfOverflow::Application.routes.draw do
  root :to => 'questions#index'

  resources :users, :except => :index
  resources :questions do
    post '/upvote' => 'votes#upvote'
    post '/downvote' => 'votes#downvote'
  end
  resources :answers, :only => [:create, :new, :edit, :update, :destroy, :show] do
    post '/upvote' => 'votes#upvote'
    post '/downvote' => 'votes#downvote'
  end

  resource :session, :only => [:create, :destroy]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      elsif user.user?
        can [:read,:create], :all
        can [:update, :delete], :all if :user_id == user.id
      else
        can :read, :all
      end
    
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :description, :user_id, :answerable_type, :answerable_id, :question_id

  belongs_to :user
  belongs_to :answerable, :polymorphic => true
  has_many :answers, :as => :answerable
  has_many :votes, :as => :votable

  validates :description, :presence => true

  def sum_votes
    Vote.where("votable_id = ? AND votable_type = 'Answer'", self.id).sum('counter')
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :description, :user_id

  belongs_to :user
  has_many :answers, :as => :answerable
  has_many :votes, :as => :votable

  validates :title, :presence => true
  validates :title, :uniqueness => true
  validates :description, :presence => true

  def sum_votes
    Vote.where("votable_id = ? AND votable_type = 'Question'", self.id).sum('counter')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :email
  
  has_secure_password

  has_many :questions
  has_many :answers
  has_many :votes

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :username, :presence => true
  validates :username, :uniqueness => true
  validates :email, :presence => true
  validates :email, :uniqueness => true

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :counter, :votable_type, :votable_id, :user_id

  belongs_to :votable, :polymorphic => true
  belongs_to :user
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer = Answer.create(params[:answer])
    @answer.update_attributes(:user_id => session[:id], :answerable_type => params[:answer][:answerable_type], :answerable_id => params[:answer][:answerable_id].to_i, :question_id => params[:answer][:question_id])
    @question = Question.find(@answer.question_id)
    redirect_to @question
  end

  def new
    @answer = Answer.new
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = Question.find(@answer.question_id)
  end

  def show
    @answer = Answer.find(params[:id])
    @question = Question.find(@answer.question_id)
    redirect_to @question
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update_attributes(params[:answer])
    redirect_to @answer
  end

  def destroy
    Answer.destroy(params[:id])
    @user = User.find(session[:id])
    redirect_to @user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @question = Question.all
  end

  def create
   @question = Question.create(params[:question])
   @question.update_attributes(:user_id => session[:id])
   redirect_to @question
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def show
    @question = Question.find(params[:id])
    @answers = Answer.where(:answerable_type => "Question", :answerable_id => @question.id)
    @answer = Answer.new
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(params[:question])
    redirect_to @question
  end

  def destroy
    Question.destroy(params[:id])
    @user = User.find(session[:id])
    redirect_to @user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_email(params["email"])
    if @user
      if @user.password = params["password"]
       session[:id] = @user.id
       redirect_to @user
      end
    else
       render :nothing => true, status: :bad_request
    end
  end

  def destroy
    session.clear
    redirect_to questions_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.create(params[:user])
    if @user.id.nil?
      redirect_to root_path
    else 
      session[:id] = @user.id
      redirect_to @user
    end
  end

  def new
    @user = User.new
  end

  def edit

  end

  def show
    @user = User.find(session[:id])
    @users_questions = Question.where(:user_id => @user.id)
    @users_answers = Answer.where(:user_id => @user.id)
  end

  def update

  end

  def destroy

  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  include ApplicationHelper
  include VotesHelper


  def upvote
    voter(params, 1)
  end

  def downvote
    voter(params, -1)
  end

  private

  def voted(votable)
    votable.votes.find_by_user_id(current_user.id)
  end


  def voter(params, score)
    votable, q_id = votable_id_find(params)[0], votable_id_find(params)[1]
    vote = voted(votable)
    if voted(votable)
      user_vote = votable.votes.find_by_user_id(current_user.id)
      if vote.counter == 0
        Vote.update(user_vote.id, :counter => score)
      else
        Vote.update(user_vote.id, :counter => 0)
      end
    else
      votable.votes << Vote.create(user_id: current_user.id, counter: score)
    end
    question = Question.find(q_id)
    redirect_to question_path(question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    return unless session[:id]
    @current_user ||= User.find(session[:id])
  end
  
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper

  def votable_id_find(params)
    votable_id = params[:answer_id] 
    if votable_id
      votable = Answer.find(votable_id)
      q_id = votable.question_id
    else
      votable_id = params[:question_id] 
      votable = Question.find(votable_id)
      q_id = votable.id
    end
    [votable, q_id]
  end
end

app/views/answers/_answer_form.html.erb
<div class="answer_form">
  <%= form_for Answer.create do |form| %>
    <p><%= form.label :description %>:</p>
    <%= h form.text_field :description %><br>
    <%= form.hidden_field :answerable_type, :value => answerable.class %>
    <%= form.hidden_field :answerable_id, :value => answerable.id %>
    <%= form.hidden_field :question_id, :value => question.id %>
    <p><%= form.submit %></p>
  <% end %>
</div>

app/views/answers/delete.html.erb
delete.html.erb

app/views/answers/edit.html.erb
<%= render 'answer_form', :locals => [@answer, @question] %>

app/views/answers/show.html.erb
show.html.erb

app/views/answers/update.html.erb
update.html.erb

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <% unless current_user %>
      <li><%= link_to "Login", session_path, :method => :post %></li>
      <li><%= link_to "Signup", new_user_path %></li>
    <% end %>
    <% if current_user %>
      <li><%= link_to "Logout", session_path, :method => :delete %></li>
      <li><%= link_to "Profile", user_path(current_user) %></li>
      <li><%= link_to "Home", questions_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SfOverflow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/questions/_question_form.html.erb
<div class="question_form">
  <%= form_for @question do |form| %>
    <p><%= form.label :title %>:</p>
    <%= h form.text_field :title %><br>
    <p><%= form.label :description %>:</p>
    <%= h form.text_field :description %><br>
    <p><%= form.submit %></p>
  <% end %>
</div>

app/views/questions/destroy.html.erb
delete.html.erb

app/views/questions/edit.html.erb
<%= render 'questions/question_form', :locals => @question %>

app/views/questions/index.html.erb
<h1> SF Overflow </h1>


<%= render "users/loginform" %>

<% @question.each do |question| %>
<p><%= link_to question.title, question %></p>
<% end %>

app/views/questions/new.html.erb
<%= render '/questions/question_form', :locals => @question %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.description %></p>
<span id="question-vote"><%= @question.sum_votes %></span>
<span class="question-button-up"><%= button_to "Upvote", question_upvote_path(@question) %> </span>
<span class="question-button-down"><%= button_to "Downvote", question_downvote_path(@question) %> </span>
<p><%= render '/answers/answer_form', :answer => @answer, :answerable => @question, :question => @question %></p>
<% @answers.each do |answer| %>
<div class="answer">
  <span><%= answer.description %></span>
  <span class="answer-vote"><%= answer.sum_votes %></span>
  <span><%= button_to "Upvote", answer_upvote_path(answer) %> 
  </span>
  <span><%= button_to "Downvote", answer_downvote_path(answer) %> </span>
  <span>upvote</span>
  <%= render '/answers/answer_form', :answer => answer, :answerable => answer, :question => @question %>
</div>
<% end %>

app/views/questions/update.html.erb
update.html.erb

app/views/users/_loginform.html.erb
<div class="login_form">
  <%= form_tag session_path, :method => 'post' do %>
    <p><%= label_tag(:email, "Email:") %></p>
    <p><%= h text_field_tag(:email) %></p>
    <p><%= label_tag(:password, "Password:") %></p>
    <p><%= h password_field_tag(:password) %></p> 
    <p><%= submit_tag("Submit") %></p>
  <% end %>
</div>

app/views/users/_signup_form.html.erb
<div class="signup_form">
  <%= form_for @user do |form| %>
    <%= form.label :username %>
    <%= h form.text_field :username %>
    <%= form.label :email %>
    <%= h form.text_field :email %>
    <%= form.label :password %>
    <%= h form.password_field :password %>
    <%= form.submit %>
  <% end %>
</div>

app/views/users/create.html.erb
"it works"

app/views/users/delete.html.erb
delete.html.erb

app/views/users/edit.html.erb
edit.html.erb

app/views/users/new.html.erb
<%= render 'users/signup_form' %>

app/views/users/show.html.erb
<h2>Welcome, <%= @user.username %></h2>

<div class="submit_question">
  <%= link_to "Submit a Question", new_question_path %>
</div>

<h3>Your Questions</h3>
<div class="profile_questions">
  <% @users_questions.each do |question| %>
    <%= link_to question.title, question %> 
    <%= link_to "Edit", edit_question_path(question) %>
    <%= link_to "Delete", question_path(question), :method => :delete %>
    <br><br>
  <% end %>
</div>

<h3>Your Answers</h3>
<div class="profile_answers">
  <% @users_answers.each do |answer| %>
    <%= link_to answer.description, answer %> 
    <%= link_to "Edit", edit_answer_path(answer) %>
    <%= link_to "Delete", answer_path(answer), :method => :delete %>
    <br><br>
  <% end %>
</div>

app/views/users/update.html.erb
update.html.erb